version: "2.27"

name: smm_shelter

services:
#   frontend:
#     container_name: frontend
#     restart: always
#     build: frontend
#     environment:
#       - BACKEND_LINK=0.0.0.0:8002
#     ports:
#       - 8080:8080
#     depends_on:
#       - backend


  # backend:
  #   container_name: backend
  #   restart: always
  #   build: backend
  #   environment:
  #     - POSTGRES_WEATHER_NAME_SERVICE=postgres-pets-service
  #     - POSTGRES_WEATHER_DB=pets-service
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - postgres-pets-service
  #   ports:
  #     - 8002:8000


  postgres-pets-service:
    container_name: postgres-pets-service
    restart: always
    image: postgres:16
    volumes:
      - ./dump/dump_pets.sql:/docker-entrypoint-initdb.d/dump_pets.sql
    environment:
      - POSTGRES_DB=pets-service
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5433
    command: 
      - -p 5433
